name: chatwoot_sdk
description: A flutter client sdk for chatwoot. Integrate Chatwoot flutter client into your flutter app and talk to your visitors/users in real time.
version: 0.0.9
publish_to: none
homepage: https://github.com/chatwoot/chatwoot-flutter-sdk

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_ui:
    git:
      url: https://github.com/terraka-io/flutter_chat_ui.git
      ref: 9981a263f8c15f5991be21aaee1a88bf78dd864c
    # path: ../flutter_chat_ui
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  web_socket_channel: ^3.0.1
  json_annotation: ^4.9.0
  dio: ^5.7.0
  equatable: ^2.0.5
  riverpod: ^2.6.1
  synchronized: ^3.3.0+3
  intl: ^0.19.0
  flutter_chat_types: ^3.6.2
  stream_channel: ^2.1.2
  async: ^2.11.0
  webview_flutter: ^4.10.0
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.4
  win32: ^5.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
